[env:feather_m0]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino

check_tool = cppcheck
check_flags =
  cppcheck: --skip-packages


lib_deps =
  adafruit/Adafruit BME280 Library
  adafruit/Adafruit Unified Sensor
  arduino-libraries/WiFi101